#!/bin/bash

# Check if there is an argument
if [ $# -ne 1 ]; then
    echo "You need an argument" >/dev/stderr
    exit 1
fi

# Check if the .tsv file exists
if [ ! -s "$1" ]; then
    echo "$1 is not a file or has zero length" >/dev/stderr
    exit 2
fi

DATA_FILE="$1"

# Create an array to hold the count of each month
declare -A month_count


# Initialize the month_count array with a count of 0 for all 12 months
for ((month=1; month<=12; month++)); do
    month_count[$(printf "%02d" $month)]=0
done


# Read the file line by line and count the occurrence of each month
awk -F'\t' 'NR>1 {
    month = sprintf("%02d", $6);
    month_count[month]++
} END {
    for (month in month_count) {
        print month_count[month], month
    }
}' "$DATA_FILE" | sort -k2 > tmp_file


# Calculate median using ternary operator
MEDIAN=$(sort -n tmp_file | awk '{
    a[NR] = $1
} END {
    print (NR%2 == 0) ? (a[NR/2] + a[NR/2+1]) / 2 : a[(NR+1)/2]
}')

# Calculate median absolute deviation (MAD) using ternary operator
MAD=$( gawk -v median="$MEDIAN" '{
    abs = ($1 > median) ? $1 - median : median - $1;
    a[NR] = abs
} END {
    asort(a);
    print (NR%2 == 0) ? (a[NR/2] + a[NR/2+1]) / 2 : a[(NR+1)/2]
}' tmp_file )

echo "Median: $MEDIAN"
echo "MAD: $MAD"

# Print header
echo -e "Month\tIncidents\tDeviation"

# Print table with each row showing the month, incidents number, and symbol
awk -v median="$MEDIAN" -v mad="$MAD" 'BEGIN {
    OFS = "\t"
    months = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec"
}
NR > 0 {
    #using ternary operator to get the symbol:++ -- ""
    dev = ($1 >= median + mad || $1 <= median - mad) ? ($1 >= median + mad ? "++" : "--") : "";
    
    #Extract three-letter month abbreviation
    month = substr(months, ($2 - 1) * 4 + 1, 3);
    print month, $1, dev
}' tmp_file | column -t

# Remove temporary file
rm -f tmp_file
